In [4]:
class Employee:
    no_of_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(femployees, n):
        add = 0
        for employee in femployees:
            add += employee.salary
        return add / n


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

def main():
    femployees = []
    employees = []
    femp1 = FulltimeEmployee("Kiran", "Kumar", 145000, "Team Lead")
    femployees.append(femp1)
    femp2 = FulltimeEmployee("Manideep", "Reddy", 180000, "Delivery Manager")
    femployees.append(femp2)
    femp3 = FulltimeEmployee("Sushma", "Shetty", 155000, "Project Lead")
    femployees.append(femp3)
    femp4 = FulltimeEmployee("Vaishnavi", "Reddy", 180000, "hr")
    femployees.append(femp4)
    employee1 = Employee("Mahitha", "Reddy", 96000, "Developer")
    employees.append(employee1)
    employee2 = Employee("Bharat", "Kumar", 50000, "Tester")
    employees.append(employee2)
    print("Average salary of fulltimeemployees:", FulltimeEmployee.average_salary(femployees, (len(femployees))))
    print("Average salary of employees:", Employee.average_salary(employees, (len(employees))))

if __name__ == "__main__":
    main()

Average salary of fulltimeemployees: 165000.0
Average salary of employees: 73000.0


In [2]:
import numpy as np
z = np.random.uniform(1, 20, 20)
m = z.reshape(4, 5)
print(m)

m = np.where(m == np.max(m, axis=1, keepdims=True), 0, m)
print(m)

[[11.74711372  8.78972146  4.49327847  7.24511314  1.72481871]
 [ 1.38598877 15.03027875 17.05554223  3.49842178  2.48984489]
 [ 4.79082764  7.93415287 16.84857495 13.66563398 11.70719427]
 [ 8.98347503  7.56253143 11.25735771  9.74615572 15.44610462]]
[[ 0.          8.78972146  4.49327847  7.24511314  1.72481871]
 [ 1.38598877 15.03027875  0.          3.49842178  2.48984489]
 [ 4.79082764  7.93415287  0.         13.66563398 11.70719427]
 [ 8.98347503  7.56253143 11.25735771  9.74615572  0.        ]]
